### PR TITLE
[Install] Upgrade to 1.2.0-beta

### LINKED ISSUE #31: [Install] Upgrade to Citrix 1.2.0-beta
**Enhancement Description**
The current version of the adapter runs Citrix Service Mesh 1.1.0-beta. 1.2.0-beta is currently available.

### PR DESCRIPTION
**Pull request by leecalcote**
Signed-off-by: leecalcote <leecalcote@gmail.com>

Fixes #31 and includes a name change from 'cpx' to 'citrix service mesh'.

### CODE REVIEW

**Comment by dheerajng** [comment]
Any idea why Error check is failing?
```
##[error]Process completed with exit code 1.
```

**Comment by kushthedude** [comment]
We need to catch all errors in this functions 
```sh
cpx/cpx.go:96:11:	os.Setenv("KUBECONFIG", configPath)
18
cpx/cpx.go:358:28:	iClient.deleteResource(ctx, res, data)
19
cpx/cpx.go:460:29:	defer iClient.applyCpxCRDs(ctx, arReq.DeleteOp)
20
cpx/cpx.go:512:24:	defer resp.Body.Close()
21
cpx/cpx.go:697:27:	iClient.createNamespace(ctx, arReq.Namespace)
22
cpx/cpx.go:704:20:	go iClient.runVet()
23
cpx/cpx.go:835:25:	defer yamlDecoder.Close()
24
cpx/install-istio.go:87:24:	defer resp.Body.Close()
25
cpx/install-istio.go:144:19:	defer dFile.Close()
26
cpx/install-istio.go:153:23:	defer resp.Body.Close()
27
cpx/install-istio.go:184:22:	defer gzReader.Close()
28
cpx/install-istio.go:223:19:	fileAtLoc.Close()
29
cpx/install-istio.go:344:23:	defer resp.Body.Close()
30
cpx/install-istio.go:352:18:	defer out.Close()
```

**Comment by dheerajng** [comment]
> We need to catch all errors in these functions
> 
> ```shell
> cpx/cpx.go:96:11:	os.Setenv("KUBECONFIG", configPath)
> 
> cpx/cpx.go:358:28:	iClient.deleteResource(ctx, res, data)
> 
> cpx/cpx.go:460:29:	defer iClient.applyCpxCRDs(ctx, arReq.DeleteOp)
> 
> cpx/cpx.go:512:24:	defer resp.Body.Close()
> 
> cpx/cpx.go:697:27:	iClient.createNamespace(ctx, arReq.Namespace)
> 
> cpx/cpx.go:704:20:	go iClient.runVet()
> 
> cpx/cpx.go:835:25:	defer yamlDecoder.Close()
> 
> cpx/install-istio.go:87:24:	defer resp.Body.Close()
> 
> cpx/install-istio.go:144:19:	defer dFile.Close()
> 
> cpx/install-istio.go:153:23:	defer resp.Body.Close()
> 
> cpx/install-istio.go:184:22:	defer gzReader.Close()
> 
> cpx/install-istio.go:223:19:	fileAtLoc.Close()
> 
> cpx/install-istio.go:344:23:	defer resp.Body.Close()
> 
> cpx/install-istio.go:352:18:	defer out.Close()
> ```

Okay. Got it. Will fix it.

**Comment by dheerajng** [comment]
Hi @leecalcote , created another PR #33 to fix above issue and handle all errors reported during `Error Check` stage.

**Comment by leecalcote** [comment]
@dheerajng excellent. 👍

**Pull request closed without merging**
